ecommerce-webapp/app/user/routes.py
import requests
from werkzeug.exceptions import ServiceUnavailable
import hashlib

from flask import abort, Blueprint, flash, render_template, redirect, request, url_for, session
from flask_login import current_user, login_user, logout_user

from app import login_manager
from app.config import Services
from app.models import Customer
from app.shoppingcart.routes import merge_cart


blueprint = Blueprint('user', __name__, template_folder='templates', url_prefix='/user')


@login_manager.user_loader
def load_user(customer_id):
    try:
        customer = requests.get(Services.CUSTOMER.value + '/customer/{}'.format(customer_id))
    except requests.ConnectionError:
        return None

    if customer.status_code == 404:
        return None
    return Customer(customer.json())


@blueprint.route('/<user_id>')
def profile(user_id):
    user = load_user(user_id)
    return render_template('profile.html', user=user)


@blueprint.route('/account')
def account():
    if current_user.is_authenticated:
        return render_template('account.html')
    else:
        return redirect(url_for('ecommerce.index'))


@blueprint.route('/articles')
def articles():
    if current_user.is_authenticated:
        try:
            response = requests.get(Services.CATALOG.value + '/seller/{}'.format(current_user.username))

            if response.status_code != 200:
                abort(response.status_code)
        except requests.ConnectionError:
            raise ServiceUnavailable('Catalog service is unavailable.')

        articles = response.json()

        return render_template('articles.html', articles=articles)
    else:
        return redirect(url_for('ecommerce.index'))


@blueprint.route('/orders')
def orders():
    if current_user.is_authenticated:
        try:
            response = requests.get(Services.ORDER.value + '/customer/{}'.format(current_user.username))
            inbound = response.json() if response.status_code == 200 else {}

            response = requests.get(Services.ORDER.value + '/seller/{}'.format(current_user.username))
            outbound = response.json() if response.status_code == 200 else {}
        except requests.ConnectionError:
            raise ServiceUnavailable('Order service is unavailable.')

        return render_template('orders.html', inbound=inbound, outbound=outbound)
    else:
        return redirect(url_for('ecommerce.index'))


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # Check if an user is already logged in.
    if current_user.is_authenticated:
        return redirect(url_for('ecommerce.index'))

    # Validate login request
    if request.method == 'POST':
        customer_username = request.form['username']
        customer_password = request.form['password']

        # Connect to customer service
        try:
            customer = requests.get(Services.CUSTOMER.value + '/customer/{}'.format(customer_username))
        except requests.ConnectionError:
            raise ServiceUnavailable('Customer service is unavailable.')

        if customer.status_code == 404:
            flash('No customer exists with this ID.', 'danger')
        else:
            customer = Customer(customer.json())
            password_hash = hashlib.sha256(customer_password.encode('UTF-8')).hexdigest()

            if customer.password == password_hash:
                login_user(customer)
                merge_cart(customer.id)
                return redirect(url_for('ecommerce.index'))
            else:
                flash('Invalid password.', 'danger')

    return render_template('login.html')


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # Check if an user is already logged in.
    if current_user.is_authenticated:
        return redirect(url_for('ecommerce.index'))

    # Validate login request
    if request.method == 'POST':
        customer_data = {
            'username': request.form['username'],
            'name': request.form['name'],
            'email': request.form['email'],
            'password': hashlib.sha256(request.form['password'].encode('UTF-8')).hexdigest()
        }

        try:
            customer = requests.post(Services.CUSTOMER.value + '/customers', json=customer_data)
        except requests.ConnectionError:
            raise ServiceUnavailable('Customer service is unavailable.')

        if 'error' in customer.json():
            flash(customer.json()['error'], 'danger')
        else:
            flash('Registration successful! You can now login.', 'success')
            return redirect(url_for('user.login'))

    return render_template('register.html')


@blueprint.route('/logout')
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('ecommerce.index'))


@blueprint.route('/delete-account', methods=['POST'])
def delete_account():
    # Check if an user is logged in.
    if not current_user.is_authenticated:
        return abort(400)

    # Delete the user's shopping cart
    try:
        response = requests.delete(Services.CART.value + '/cart/{}'.format(current_user.username))

        if response.status_code != 200:
            return abort(response.status_code)
    except requests.ConnectionError:
        raise ServiceUnavailable('Shopping cart service is unavailable.')

    # Delete all articles being sold by the user
    try:
        response = requests.delete(Services.CATALOG.value + '/seller/{}'.format(current_user.username))

        if response.status_code != 200:
            return abort(response.status_code)
    except requests.ConnectionError:
        raise ServiceUnavailable('Catalog service is unavailable.')

    # TODO: Delete this for production environments !
    #  Only meant to keep database clean when generating random orders during testing
    # Delete all orders from the user
    try:
        response = requests.delete(Services.ORDER.value + '/customer/{}'.format(current_user.username))
        if response.status_code != 200:
            return abort(response.status_code)

        response = requests.delete(Services.ORDER.value + '/seller/{}'.format(current_user.username))
        if response.status_code != 200:
            return abort(response.status_code)
    except requests.ConnectionError:
        raise ServiceUnavailable('Order service is unavailable.')

    # Delete the user account
    try:
        response = requests.delete(Services.CUSTOMER.value + '/customer/{}'.format(current_user.username))

        if response.status_code != 200:
            return abort(response.status_code)
    except requests.ConnectionError:
        raise ServiceUnavailable('Customer service is unavailable.')

    return redirect(url_for('user.logout'))

ecommerce-webapp/app/user/templates/account.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}

{% block body %}
    <form action="{{ url_for('user.delete_account') }}" method="POST">
        <button type="submit" class="btn btn-danger">Delete Account</button>
    </form>
{% endblock %}

ecommerce-webapp/app/user/templates/articles.html
{% extends 'layout.html' %}
{% set title = 'My Articles' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('static', filename='dist/datatables-1.10.18/datatables.min.css') }}">
{% endblock %}

{% macro display_quantity(quantity) %}
    {% if quantity <= 5 %}
        {% set color = 'red' %}
    {% elif quantity < 30 %}
        {% set color = 'orange' %}
    {% else %}
        {% set color = 'green' %}
    {% endif %}

    <label style="color: {{ color }};">{{ quantity }}</label>
{% endmacro %}

{% block body %}
    <h2>Articles</h2>
    <table id="articles" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Price</th>
            <th>Quantity</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.article_id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.price }}</td>
                <td>{{ display_quantity(article.quantity) }}</td>
                <td>
                    <a href="#"><span class="glyphicon glyphicon-search"></span></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2>Create new article</h2>
    <form action="{{ url_for('ecommerce.create_article') }}" method="POST">
        <div class="input-group col-xs-12 col-md-4">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Title">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" placeholder="Description"></textarea>
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name="image">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <span class="input-group-addon">$</span>
            <input type="text" class="form-control" id="price" name="price" placeholder="0.00">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="quantity">Quantity</label>
            <input type="text" class="form-control" id="quantity" name="quantity" placeholder="1">
        </div>
        <button type="submit" class="btn btn-primary">Sell article</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='dist/datatables-1.10.18/datatables.min.js') }}"></script>
    <script language="javascript">
        $(document).ready(function () {
            $('#articles').DataTable();
        });
    </script>
{% endblock %}

ecommerce-webapp/app/user/templates/login.html
{% extends 'layout.html' %}
{% set title = 'Login' %}

{% block body %}
    <h3>{{ title }}</h3>

    <form action="{{ url_for('user.login') }}" method="POST">
        <div class="input-group col-xs-12 col-md-4">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Username">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <p>Not a member yet? <a href="{{ url_for('user.register') }}">Create an account!</a></p>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

ecommerce-webapp/app/user/templates/orders.html
{% extends 'layout.html' %}
{% set title = 'Home' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('static', filename='dist/datatables-1.10.18/datatables.min.css') }}">
{% endblock %}

{% macro display_status(status_code) %}
    {% set color = 'red' if status_code == 'CLOSED' else 'green' %}
    <label style="color: {{ color }};">{{ status_code }}</label>
{% endmacro %}

{% macro display_update(date) %}
    {{ date if date is not none else 'No updates found' }}
{% endmacro %}

{% block body %}
    <h2>Inbound Orders</h2>
    <table id="inbound-orders" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Created on</th>
            <th>Status</th>
            <th>Last updated on</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for order in inbound %}
            <tr>
                <td>{{ order['order_id'] }}</td>
                <td>{{ order['created_date'] }}</td>
                <td>{{ display_status(order['status']) }}</td>
                <td>{{ display_update(order['updated_date']) }}</td>
                <td>
                    <a href="#"><span class="glyphicon glyphicon-search"></span></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2>Outbound Orders</h2>
    <table id="outbound-orders" class="table" style="width:100%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Created on</th>
            <th>Status</th>
            <th>Last updated on</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for order in outbound %}
            <tr>
                <td>{{ order['order_id'] }}</td>
                <td>{{ order['created_date'] }}</td>
                <td>{{ display_status(order['status']) }}</td>
                <td>{{ display_update(order['updated_date']) }}</td>
                <td>
                    <a href="#"><span class="glyphicon glyphicon-search"></span></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='dist/datatables-1.10.18/datatables.min.js') }}"></script>
    <script language="javascript">
        $(document).ready(function () {
            $('#inbound-orders').DataTable();
        });

        $(document).ready(function () {
            $('#outbound-orders').DataTable();
        });
    </script>
{% endblock %}

ecommerce-webapp/app/user/templates/profile.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}

{% block body %}
{% endblock %}

ecommerce-webapp/app/user/templates/register.html
{% extends 'layout.html' %}
{% set title = 'Register' %}

{% block body %}
    <h3>{{ title }}</h3>

    <form action="{{ url_for('user.register') }}" method="POST">
        <div class="input-group col-xs-12 col-md-4">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="j_doe">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="name">Full name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="John Doe">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="john.doe@outlook.com">
        </div>
        <div class="input-group col-xs-12 col-md-4">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <p>Already a member? <a href="{{ url_for('user.login') }}">Login!</a></p>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}